version: '3'

services:
  api:
    image: "tianlin976/user-server"
    mem_limit: 128m
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_SERVER_IP}:${MONGODB_LOCAL_PORT}/
      - NODE_ENV=dev
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

  client:
    image: "tianlin976/user-client"
    mem_limit: 128m
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
