version: '3'

services:
  mongo:
    image: 'mongo:latest'
    restart: always
    env_file:
      - dev.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - mongo:/data/db
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT

  # nginx:
  #   depends_on:
  #     - api
  #     - client
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - "3080:80"

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - dev.env
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:${MONGODB_LOCAL_PORT}/
      - NODE_ENV=dev
    depends_on:
      - mongo

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    env_file:
      - dev.env
    volumes:
      - /app/node_modules
      - /app/dist
      - ./client:/app
    ports:
      - "80:80"

volumes:
  mongo:
