version: '3'

services:
  mongo:
    image: 'mongo:latest'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - mongo:/data/db
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    networks:
      - network

  nginx:
    depends_on:
      - api
      - client
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - network

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:${MONGODB_LOCAL_PORT}/
      - NODE_ENV=dev
    depends_on:
      - mongo
    networks:
      - network

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  mongo:
