apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: ClusterIP
  selector:
    name: web-service
  ports:
  - name: web-service-port
    protocol: TCP
    port: 80
    targetPort: client-port