apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-persistent-volume-claim
spec:
  capacity:
    storage: 129M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2