apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: ClusterIP
  selector:
    name: server-service
  ports:
  - name: server-service-port
    protocol: TCP
    port: 4000
    targetPort: server-port